### PR TITLE
Optional filters for DUMP_PARAMETERS macro

### PR DESCRIPTION
**Pull request by FatalBulletHit**
Adding optional name and value filters to the `DUMP_PARAMETERS` macro.
This also hides the clutter that `['configfile'].config` and `['configfile'].settings` cause in the console by default (can be disabled by calling the macro with `SHOW_CFG=1`).
Should make debugging easier and faster.
Tested on my V2.4r2 running MainsailOS.

### CODE REVIEW

**Comment by FatalBulletHit** [comment]
- renamed `DUMP_PARAMETERS` to `DUMP_VARIABLES`
- made the my filter if-statement less messy
- changed output to do a single `action_respond_info()` call, this decreases output duration (took some inspiration from kiauh lol)
- added usage examples

I also added `GET_VARIABLE` which lets you get value and type of more nested dictionaries and lists, should also aid debugging. ^^

**Comment by AndrewEllis93** [comment]
Both macros work well! Thanks for the contribution!

Two minor things before merging:

1 - The GET_VARIABLE macro is missing the config header:
```
[gcode_macro GET_VARIABLE]
gcode:
```
2 - Can you split out the "usage" section into "arguments" and "examples" please? [Example of how I've done it for TEST_SPEED](https://github.com/AndrewEllis93/Print-Tuning-Guide/blob/main/articles/determining_max_speeds_accels.md#available-arguments-omitting-any-will-use-the-default-value), (though you can just call them "arguments" and "examples" and skip the other verbiage.)
   - And bold them with sub-section headers (e.g. `## Arguments` or `### Arguments`) - no biggie though, just nitpicky formatting stuff, also happy to just fix that up afterwards.

**Comment by AndrewEllis93** [comment]
Merging to WIP branch, feelin' spicy so I'm going to make the discussed changes

**Comment by AndrewEllis93** [comment]
Made those edits + updated table of contents. Thanks again for the contribution!

**Comment by FatalBulletHit** [comment]
Thanks for the fix, your guide is great and helped me a lot, glad I was able to give something back! :)

**Pull request merged**
