### PR TITLE
add start/end notifications for easier spotting and parsing of klippy.log

### PR DESCRIPTION
**Pull request by geoffrey-young**
….log

### CODE REVIEW

**Comment by AndrewEllis93** [comment]
Thanks for your contribution!

**Comment by AndrewEllis93** [comment]
Actually just noticed this, the "end" text gets spat out at the beginning. I think this is a quirk of how Jinja works, it's all interpreted right at the beginning. 

```
Recv: // TEST_SPEED: starting 5 iterations at speed 450, accel 10000
Recv: // TEST_SPEED: end
```

The start message works though so I'll keep that as is

**Comment by geoffrey-young** [comment]
ugh, you’re right. glad you noticed :)

--Geoff

On Feb 16, 2022, at 6:00 PM, AndrewEllis93 ***@***.***> wrote:

﻿
Actually just noticed this, the "end" text gets spat out at the beginning. I think this is a quirk of how Jinja works, it's all interpreted right at the beginning.

Recv: // TEST_SPEED: starting 5 iterations at speed 450, accel 10000
Recv: // TEST_SPEED: end
The start message works though so I'll keep that as is

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by blalor** [comment]
You can just use the [`RESPOND`](https://www.klipper3d.org/G-Codes.html#respond_1)  or `M118` gcodes, assuming `[respond]` is enabled in the config.

**Pull request merged**
