### PR TITLE
improved loop for testing speeds

### PR DESCRIPTION
**Pull request by legend069**
max_accel and max_velocity are stored as float values in klipper code
added smaller constraint box apart of main loop
added option to test the z accuracy/speed.

have not figured out how to output the remaining loops to the terminal ( this can be usefull for when running long loops )
i would like to capture the "mcu" data from klipper and auto calculate the steps difference also.

### CODE REVIEW

**Comment by AndrewEllis93** [comment]
Just acknowledging this.. will review when I get some time

**Comment by AndrewEllis93** [comment]
Going to start messing with this tonight. Sorry for the long delay, been in a bit of a rut

**Comment by AndrewEllis93** [comment]
Is this ready for primetime? 

I see some comments in here like "work in progress", "need to add printer z velocity ?" and a lot of extraneous commented-out leftovers that are muddying things.

Just my two cents, tuning Z speed isn't particularly advantageous. In fact I've usually advocated to set it low and just forget about it since it's not worth the trouble. But if you're willing to get it up to snuff*, though, I'm not against merging it.

*What I mean by that:
- Instructions/documentation are an necessity for me to merge. I don't mind prettying things up, but I don't want to have to reverse engineer your macro here to try and document it.
- It needs to be **finalized** and without the extraneous leftovers and comments. This still looks like a work in progress with the leftover comments etc.
- I would prefer Z speed testing to be a completely separate macro (named TEST_SPEED_Z) that JUST tests Z speeds, personally. We could do that separately (or not at all) and just look at implementing the X/Y patterns if you want (though I have not tested them yet).

**Comment by AndrewEllis93** [comment]
Just ran this today, I quite like the new pattern! At the very least I think I will incorporate that part

**Comment by legend069** [comment]
> Is this ready for primetime?
> 
> I see some comments in here like "work in progress", "need to add printer z velocity ?" and a lot of extraneous commented-out leftovers that are muddying things.
> 
> Just my two cents, tuning Z speed isn't particularly advantageous. In fact I've usually advocated to set it low and just forget about it since it's not worth the trouble. But if you're willing to get it up to snuff*, though, I'm not against merging it.
> 
> *What I mean by that:
> 
>     * Instructions/documentation are an necessity for me to merge. I don't mind prettying things up/re-wording things to fit, but I don't want to have to reverse engineer your macro here to try and document it.
> 
>     * It needs to be **finalized** and without the extraneous leftovers and comments. This still looks like a work in progress with the leftover comments etc.
> 
>     * I would prefer Z speed testing to be a completely separate macro (named TEST_SPEED_Z) that JUST tests Z speeds, personally. We could do that separately (or not at all) and just look at implementing the X/Y patterns if you want (though I have not tested them yet).

no it's not ready from prime time yet,
i still would like to figure out how to add the "remaining loops" feature and the "skipped steps" feature 

i agree the testing z speed part can be in a different macro. (I'm just not a fan of having lots of files in my config )
i would like to keep it though as its a little usefull, to see if Z skips steps. i have not experimented with it that much though.

if you have any ideas on how to grab the data from "get_position" :MCU and seperate it from a string to a string and integers 
let me know my python is a bit rusty.

**Comment by legend069** [comment]
> Just ran this today, I quite like the new pattern! At the very least I think I will incorporate that part

yes the smaller constraint loops is my favorite as that's what is more likely to cause a skip in micro steps from acceleration 
the larger loop is more likely to cause a skip in steps from speed

I've considered adding a "zig-zag" movement loop too that would put more strain on x movement.
then rotate the "zig-zag" movement loop to put more strain on the y movements.

**Comment by AndrewEllis93** [comment]
One thing that occurred to me last night. With X/Y, if it loses position it just starts to smack against the sides. If Z started having major skipping it could crash into the bed. Could potentially be dangerous

**Comment by legend069** [comment]
> 



> sides

that is a fair point, would depend on the printer/settings, as the macro doesn't allow for z speed adjustments. if the user still have the z movement set too high in printer.cfg it can cause problems.

but then they should of already noticed that as the z movement would be super loud already.

**Comment by AndrewEllis93** [comment]
I just implemented your small pattern (though modified / cleaned up / some variables renamed etc) in commit 17d7a6377b318063434407b082419d744405297a. This is just for X/Y as it stands.

**Comment by legend069** [comment]
> I just implemented your small pattern (though modified / cleaned up / some variables renamed etc) in commit [17d7a63](https://github.com/AndrewEllis93/Print-Tuning-Guide/commit/17d7a6377b318063434407b082419d744405297a). This is just for X/Y as it stands.

I've managed to get the remaining loops feature to work.
i'm still working on getting the steps calculation feature. i think i may have to edit klipper directly, not sure yet.

regarding the z movement, i still need to test it with my machine to see if my theory is correct regarding it.
just been busy with work and other things.

**Comment by legend069** [comment]
is my test results, so it looks like testing z with the macro can help so if you're losing steps on z

below is my driver config.
```
[tmc2209 stepper_z]
uart_pin: PF2
interpolate: False
run_current: 0.849 #prev 0.976 #1.2 a little too hot on motors?
sense_resistor: 0.110
stealthchop_threshold: 0
driver_TBL: 1
driver_TOFF: 3
driver_HSTRT: 2
driver_HEND: 3
```


```
TEST_SPEED SPEED=450 ACCEL=10000 TESTSPEEDZ=True ITERATIONS=20
// mcu: stepper_x:29427 stepper_y:29471 stepper_z:7206 stepper_z1:8196 stepper_z2:8467 stepper_z3:7200
// mcu: stepper_x:29433 stepper_y:29457 stepper_z:7169 stepper_z1:8159 stepper_z2:8430 stepper_z3:7163
x: 6
y: 14
Z: 37


TEST_SPEED SPEED=450 ACCEL=10000 TESTSPEEDZ=False ITERATIONS=20
// mcu: stepper_x:29411 stepper_y:29477 stepper_z:-20 stepper_z1:941 stepper_z2:1253 stepper_z3:-1
// mcu: stepper_x:29418 stepper_y:29472 stepper_z:-33 stepper_z1:928 stepper_z2:1240 stepper_z3:-14
x: 7
y: 5
z: 13
```

**Comment by AndrewEllis93** [comment]
Hey, I think on further reflection I would prefer to leave Z testing out for the time being. Seems too liable to cause bed crashes

**Comment by AndrewEllis93** [comment]
(but thank you for the small test pattern stuff)

**Pull request closed without merging**
